[workspace]
members = [
    "day-01",
    "day-02",
    "day-03",
    "day-04",
    "day-05",
    "day-06",
    "day-07",
]

[workspace.dependencies]
anyhow = "1.0"
indoc = "1.0"
itertools = "0.10"
nom = "7.1"
